version: '3.8'

services:
  webservice-app:
    environment:
      REDIS_ADDR: "redis:6379"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
